version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
